%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\DropBox\Matlab\mlodev\semeion.xlsx Worksheet: Sayfa1
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/04/21 10:00:27

%% Import the data
clear all;
clc;
display('Lütfen veri seti aktarýlýrken bekleyiniz...');
[~, ~, raw] = xlsread('semeion.xlsx','Sayfa1');

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) ~isnumeric(x) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
semeion = cell2mat(raw);

semeionInput = semeion(:,1:256);
semeionOutput = semeion(:,257:266);

[satir sutun] = size(semeionInput);


semeionInput = semeionInput';
semeionOutput = semeionOutput';

save semeion semeionInput semeionOutput ;


%% Clear temporary variables
clearvars raw R r satir sutun semeion;
display('Veri seti baþarýyla aktarýldý.');